[package]
name = "moving-average-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
moving-average-model = { path = "../model" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strategy-api = { path = "../../../crates/strategy-api" }
